helper_dir = "src/test/helpers"
files = [
  "src/contracts/lending-pool/LendingPool.sol",
  "src/contracts/ValidatorPool.sol",
  "src/contracts/ether-router/EtherRouter.sol",
  "src/contracts/BeaconOracle.sol"
]
